name: Pipeline Demo

on:
  push:
    branches: [ "main" ]

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Validar Proyecto
        run: echo "Pipeline ejecutado exitosamente y validado"